### ISSUE TITLE
How to interpret topological distance?

### ISSUE THREAD

**Issue by micycle1** [ibaris/finance-tda#3]
How should one interpret the values in the Distance Changes chart? What does a high (versus low) value **mean**?

From section 3 of the paper `Topological tail dependence: Evidence from forecasting
realized volatility`:
>  In other words, since the absolute correlations between the stocks in St increase during turbulent periods, depicted by Fig. 9, the average distances between the data points will normally be smaller than the average distances during normal periods.

Based on this^, does a larger topological distance imply a lower correlation?

**Comment by ibaris** [comment]
Hi Micycle1,

The distances illustrates the changes between different states over time. A high value in the distance changes chart indicates a _significant_ change in the topological distance between the points in the multidimensional space representing the different states. This could mean that the relationship or dependency between the variables has undergone a shift. A low value will suggests a smaller change in the topological distance, which in turn could mean that the relationship or dependency between the variables remains relatively stable over the observed period.
But the question regarding the correlation is very interesting. I have to think about that.

**Comment by micycle1** [comment]
Ok thanks for responding, just to clarify then: the distance value spiked in 2020 (COVID), but has been much lower since then. Does that mean COVID ushered in a new state that has **persisted till the present**, or new state that **only existed during the spike**?

![image](https://github.com/user-attachments/assets/839e57a0-a5c6-4102-810c-d464af1bfe5f)

**Comment by ibaris** [comment]
Can you describe the input data, e.g. what are the variables for the distance computation?

**Comment by micycle1** [comment]
This is the example from the README😁!

**Comment by ibaris** [comment]
I´m sorry. I thought you are using some medical data related to COVID 🤣 Lets say, that some dependencies between the variables has undergone a shift: This process would lead to an spike in the distance. If the other variables catch up the same dependency shift as the first variables, the distance would decrease. One can only certainly say, that there was a shift in the dependencies.
